# fly.toml app configuration file generated for portfolio-personal-go on 2024-07-16T11:23:53+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'portfolio-personal-go'
primary_region = 'ams'

[build]
  [build.args]
    GO_VERSION = '1.22'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
